sudo: required
language: generic
services:
- docker
deploy:
- provider: script
  script: bash ./scripts/docker_push.sh
  on:
    branch: master
- provider: script
  script: bash ./scripts/docker_push.sh
  on:
    branch: develop
- provider: script
  script: bash ./scripts/docker_push.sh
  on:
    all_branches: true
    condition: "${TRAVIS_BRANCH} =~ ^release.*$"
env:
  global:
  - secure: jwpQVEBm07DbCEGPA689+YFGSNyt5UcNGMHU9S8qm/xNyyMYCN+Aaj0GspQBGHA8u/XRk7fkuz1FLfZryC0IeVAawGzo8TrsL536XncHAhz9RMqfE/46vvKZkoQ1hRDaLNVJQFJArRCTYCsnPuMW24N0FG/D0qmHI+aL9ICKbW1j6HavF0W9CCfmCbssUTdazflqqmSclvmwy0HBtKGWQWon3E6UJAxWO9dhMu7wxB6hMnXMaxqZlPk7Cf1pG59SQIgoHq1U1Mu4PWtQ8ac/ZszAStZg8DSEilzlv8bJ8OVZnFK45Qb3Z84uYTceIyQ6fDdxGFDKjl450mrS/IPf2ESt6XF4xy6HLUzpFjoZ+Os5rCx/HhsvL186g+dz9+OAIFMkhYU8UYFwkiy9pwMcmILF2m0EXUvm1WMn2inJ/dYBKj1f7kzC0Tsx/glhDBDDShHtvx7ohQfNGKvS3dbKbiE9o7yciNXkTIitq5tNa/SZW3LuzwSIKJj7viJPtQg7XN/yzVUDKtFVvr8M2QbEZ+JvGNMnOd+ECFbjocZtA8IGofTdnbZDAXJQcpacgTEMqgKT5XNdecuoqKu2rI/bvDgD90Swoa7r5UB5Kbz/LWwZI1BBFEuVRRHxKzjYb8gj0N8RhBg7sZI1ZDyYxAhxQLfDGz+5A0kysIQLXt7vuWU=
  - secure: cJ6iKtJkq1Yv+1Wl2bxHAhuIrAuT9zx+nyPrkugaqSSa7uOXMUmHSNJRKigDVjBW0kfEk17vGRSsm4gkXoxYAEkPo7/xbV+kgMLX53u5BpyJFIlmcEpd0JCKeIflUA/AARtC6M8ddO9IRjtF4UIAgKuC9REJ40LxZQ/CP8xBB/zScFnbJtVNpP5n20yEXfFnu1vbbYK0cRH/vtXZ5tHMpY8+rwaHN7DTV9aofyOrD4LjL2NAYGddhsUuajduZJw3Eh/TA6Ao/AQ8dDcJtjIqQvIjnljZSJ/+M9TS2BVC0ndBmvzmbGvfUj3PPy3+oxEpWhos13sGcjcBHwrft/rZZ5veezqLU40DiWZAKfydax4CtZJECbEgJTlbQPWbPkr8Mv94UDl4uQKEGa5t2A4Y+2FxBhgB2F0nHsjWAFkmO2mGesDWfOC+YipO/jjc4mSL8sZUMMpCL02Gb0NA8NMiSV3Id9UcYjAIebJ0E21DODXJpwcrBqZfOguL8llfRXcv+fGXabKPZBzynhKxuSbA//tkFZq2j9Poo9W/txg8iCCSpPQ5a5Ksm05C4ZUQdb3G5/7ffdFgqtVA5gaQ8Gcri3WpZSL3kB6KEndveulB3obtxsi301BaJg4I/0gu46+/XPCu+GpzEEyzX/g3xgcW1ruiSzpczE4SrMk2yOQXdkY=
